fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "sysklogd": "git://github.com/ghoneycutt/puppet-module-sysklogd.git"
    "common": "git://github.com/ghoneycutt/puppet-module-common.git"
  symlinks:
    "rsyslog": "#{source_dir}"
